name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/order-management-backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/order-management-backend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-35-175-249-255.compute-1.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop my-app || true
          docker rm my-app || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/order-management-backend:latest || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/order-management-backend:latest
          docker run -d -p 8080:8080 --name my-app ${{ secrets.DOCKER_USERNAME }}/order-management-backend:latest

